const PakistanCities = [
  "Karachi",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Gujranwala",
  "Rahim Yar Khan",
  "Multan",
  "Peshawar",
  "Sargodha",
  "Quetta",
  "Hyderabad",
  "Bahawalpur",
  "Muzafarabad",
  "Battagram",
  "Kotli",
  "Islamabad",
  "Sialkot",
  "Sukkur",
  "Larkana",
  "Shekhupura",
  "Bhimber",
  "Jhang Sadr",
  "Gujrat",
  "Mardan",
  "Malir Cantonment",
  "Kasur",
  "Mingora",
  "Dera Ghazi Khan",
  "Sahiwal",
  "Nawabshah",
  "Okara",
  "Mirpur Khas",
  "Chiniot",
  "Shahkot",
  "Kamoke",
  "Saddiqabad",
  "Burewala",
  "Jacobabad",
  "Muzafargarh",
  "Muridke",
  "Jhelum",
  "Shikarpur",
  "Hafizabad",
  "Kohat",
  "Khanpur",
  "Khuzdar",
  "Dadu",
  "Gojra",
  "Mandi Bahauddin",
  "Tando Allahyar",
  "Daska Kalan",
  "Pakpattan",
  "Bahawalnagar",
  "Tando Adam",
  "Khairpur Mir's",
  "Chishtian",
  "Abbottabad",
  "Jaranwala",
  "Ahmadpur East",
  "Vihari",
  "Kamalia",
  "Kot Addu",
  "Khushab",
  "Wazirabad",
  "Dera Ismail Khan",
  "Chakwal",
  "Swabi",
  "Lodhran",
  "Nowshera Cantonment",
  "Charsadda",
  "Jalalpur Jattan",
  "Mianwali",
  "Chaman",
  "Kandhkot",
  "Hasilpur",
  "Arifwala",
  "Mianke Mor",
  "Attock City",
  "Chichawatni",
  "Bhakkar",
  "Kharian",
  "Layyah",
  "Kambar",
  "Moro",
  "Mian Channun",
  "Turbat",
  "Shahdad Kot",
  "Bhalwal",
  "Dipalpur",
  "Badin",
  "Pano Aqil",
  "Kotri",
  "Tando Muhammad Khan",
  "Harunabad",
  "Pattoki",
  "Chenab Nagar",
  "Kahror Pakka",
  "Gujar Khan",
  "Kot Malik Barkhurdar",
  "Chuchar-kana Mandi",
  "Toba Tek Singh",
  "Narowal",
  "Shorkot",
  "Shahdadpur",
  "Shabqadar",
  "Mansehra",
  "Shujaabad",
  "Haveli Lakha",
  "Lala Musa",
  "Mailsi",
  "Shakargarh",
  "Ghotki",
  "Sibi",
  "Jampur",
  "Sambrial",
  "Sanghar",
  "Hujra Shah Muqim",
  "Kabirwala",
  "Chunian",
  "Sangla Hill",
  "Haripur",
  "Nankana Sahib",
  "Pasrur",
  "Gwadar",
  "Rajanpur",
  "Rohri",
  "Zhob",
  "Matli",
  "Rawala Kot",
  "Hadali",
  "Mirpur Mathelo",
  "Bannu",
  "Dullewala",
  "Hala",
  "Ratodero",
  "Jatoi Shimali",
  "Jauharabad",
  "Bat Khela",
  "Kot Radha Kishan",
  "Kahna Nau",
  "Mustafabad",
  "Chak Thirty-one -Eleven Left",
  "Talagang",
  "Taunsa",
  "Thatta",
  "Sarai Alamgir",
  "Usta Muhammad",
  "Kamra",
  "Umarkot",
  "Basirpur",
  "Sehwan",
  "Naushahra Virkan",
  "Fort Abbas",
  "Havelian",
  "Khairpur",
  "Dinga",
  "Ladhewala Waraich",
  "Khalabat",
  "New Badah",
  "Tank",
  "Kot Mumin",
  "Tandlianwala",
  "Chak Azam Sahu",
  "Loralai",
  "Jalalpur Pirwala",
  "Pabbi",
  "Chak Jhumra",
  "Sahiwal",
  "Renala Khurd",
  "Risalpur Cantonment",
  "Lakki",
  "Topi",
  "Hangu",
  "Pir Jo Goth",
  "Kundian",
  "Pir Mahal",
  "Khurrianwala",
  "Mehrabpur",
  "Pindi Bhattian",
  "Malakwal City",
  "Narang Mandi",
  "Malakwal",
  "Thul",
  "Pindi Gheb",
  "Zahir Pir",
  "Dunyapur",
  "Gambat",
  "Kashmor",
  "Alipur",
  "Naudero",
  "Pasni",
  "Sukheke Mandi",
  "Setharja Old",
  "Khewra",
  "Mamu Kanjan",
  "Sharqpur Sharif",
  "Digri",
  "Bhera",
  "Sakrand",
  "Tando Jam",
  "Raiwind",
  "Lalian",
  "Khairpur Tamewah",
  "Kharan",
  "Mehar",
  "Khangah Dogran",
  "Khairpur Nathan Shah",
  "Upper Dir",
  "Ghauspur",
  "Tangi",
  "Utmanzai",
  "Thal",
  "Minchianabad",
  "Garh Maharaja",
  "Jahanian Shah",
  "Mastung",
  "Mananwala",
  "Fazilpur",
  "Talamba",
  "Kunjah",
  "Jhawarian",
  "Nasirabad",
  "Nushki",
  "Sita Road",
  "Dijkot",
  "Sillanwali",
  "Kandiaro",
  "Zaida",
  "Kunri",
  "Kalat",
  "Daud Khel",
  "Mitha Tiwana",
  "Hazro City",
  "Dunga Bunga",
  "Aman Garh",
  "Karor",
  "Kot Diji",
  "Kalur Kot",
  "Murree",
  "Faqirwali",
  "Ahmadpur Sial",
  "Phalia",
  "Yazman",
  "Raja Jang",
  "Chak Five Hundred Seventy-five",
  "Pishin",
  "Chak One Hundred Twenty Nine Left",
  "Chawinda",
  "Ubauro",
  "Mithi",
  "Akora",
  "Zafarwal",
  "Kot Samaba",
  "Eminabad",
  "Kahuta",
  "Ranipur",
  "Kulachi",
  "Khanpur Mahar",
  "Hingorja",
  "Naukot",
  "Pind Dadan Khan",
  "Kanganpur",
  "Faruka",
  "Kotli Loharan",
  "Shahpur Chakar",
  "Talhar",
  "Pad Idan",
  "Kot Ghulam Muhammad",
  "Qadirpur Ran",
  "Bela",
  "Surkhpur",
  "Dhoro Naro",
  "Khangarh",
  "Sarai Naurang",
  "Gharo",
  "Bhit Shah",
  "Matari",
  "Dhanot",
  "Warah",
  "Lachi",
  "Baddomalhi",
  "Jand",
  "Chak 249 Thal Development Authority",
  "Dera Bugti",
  "Tharu Shah",
  "Naushahro Firoz",
  "Dajal",
  "Daur",
  "Bhopalwala",
  "Paharpur",
  "Bhan",
  "Mach",
  "Goth Radhan",
  "Uthal",
  "Kaleke Mandi",
  "Jiwani",
  "Johi",
  "Chhor",
  "Mangla",
  "Bhawana",
  "Shahr Sultan",
  "Jhol",
  "Sodhri",
  "Kalabagh",
  "Sinjhoro",
  "Kamar Mushani",
  "Kallar Kahar",
  "Chuhar Jamali",
  "Harnoli",
  "Sarai Sidhu",
  "Choa Saidan Shah",
  "Dadhar",
  "Darya Khan",
  "Daira Din Panah",
  "Garhiyasin",
  "Madeji",
  "Dokri",
  "Sobhodero",
  "Dalbandin",
  "Daulatpur",
  "Bhag",
  "Rasulnagar",
  "Chak",
  "Shahpur",
  "Tando Bago",
  "Bafa",
  "Karak",
  "Garhi Khairo",
  "Lakhi",
  "Gadani",
  "Surab",
  "Rojhan",
  "Ormara",
  "Chamber",
  "Kalaswala",
  "Islamkot",
  "Liliani",
  "Bhiria",
  "Mirwah Gorchani",
  "Dhaunkal",
  "Daultala",
  "Diplo",
  "Kohlu",
  "Harnai",
  "Jandiala Sher Khan",
  "Daromehar",
  "Mankera",
  "Sanjwal",
  "Miro Khan",
  "Gilgit",
  "Kot Sultan",
  "Khadro",
  "Berani",
  "Begowala",
  "Tangwani",
  "Bozdar Wada",
  "Jati",
  "Rustam",
  "Darya Khan Marri",
  "Sohbatpur",
  "Doaba",
  "Mirpur Bhtoro",
  "Sann",
  "Samaro",
  "Barkhan",
  "Bandhi",
  "Karaundi",
  "Mirpur Sakro",
  "Adilpur",
  "Bagarji",
  "Goth Phulji",
  "Rajo Khanani",
  "Alik Ghund",
  "Dinan Bashnoian Wala",
  "Jam Sahib",
  "Kandiari",
  "Kadhan",
  "Goth Garelo",
  "Nazir Town",
  "Khadan Khak",
  "Pithoro",
  "Duki",
  "Nabisar",
  "Kario Ghanwar",
  "Parachinar",

  "Bangkok",
  "Nonthaburi",
  "Nakhon Ratchasima",
  "Chiang Mai",
  "Hat Yai",
  "Udon Thani",
  "Pak Kret",
  "Khon Kaen",
  "Ubon Ratchathani",
  "Nakhon Si Thammarat",
  "Surat Thani",
  "Phuket",
  "Pattaya",
  "Chiang Rai",
  "Yala",
  "Lampang",
  "Nakhon Pathom",
  "Trang",
  "Phitsanulok",
  "Songkhla",
  "Lopburi",
  "Phra Nakhon Si Ayutthaya",
  "Samut Prakan",
  "Rayong",
  "Sakon Nakhon",
  "Sisaket",
  "Nakhon Sawan",
  "Ratchaburi",
  "Chon Buri",
  "Chachoengsao",
  "Phetchaburi",
  "Kanchanaburi",
  "Hua Hin",
  "Chiang Khong",
  "Mae Hong Son",
  "Phayao",
  "Nan",
  "Lamphun",
  "Mae Sai",
  "Sukhothai",
  "Uttaradit",
  "Phichit",
  "Kamphaeng Phet",
  "Tak",
  "Phrae",
  "Lop Buri",
  "Ang Thong",
  "Sing Buri",
  "Chai Nat",
  "Suphan Buri",
  "Nakhon Nayok",
  "Chumphon",
  "Ranong",
  "Prachuap Khiri Khan",
  "Krabi",
  "Phang Nga",
  "Satun",
  "Narathiwat",
  "Pattani",
  "Betong",
  "Ban Pong",
  "Samut Sakhon",
  "Samut Songkhram",
  "Amnat Charoen",
  "Mukdahan",
  "Nong Bua Lamphu",
  "Bueng Kan",
  "Phetchabun",
  "Chaiyaphum",
  "Roi Et",
  "Mahasarakham",
  "Kalasin",
  "Buri Ram",
  "Surin",
  "Si Racha",
  "Bang Lamung",
  "Sattahip",
  "Ko Samui",
  "Ko Pha-ngan",
  "Ko Tao",
  "Cha-am",
  "Pran Buri",
  "Bang Saphan",
  "Lang Suan",
  "Thung Song",
  "Ron Phibun",
  "Sichon",
  "Kantang",
  "Satun",
  "Phatthalung",
  "Mueang Pan",
  "Chai Prakan",
  "Doi Saket",
  "San Kamphaeng",
  "San Sai",
  "Mae Taeng",
  "Mae Rim",
  "Hang Dong",
  "Saraphi",
  "Chom Thong",
  "Wiang Haeng",
  "Doi Lo",
  "Sam Ngao",
  "Ban Tak",
  "Mae Sot",
  "Phop Phra",
  "Mae Ramat",
  "Tha Song Yang",
  "Umphang",
  "Mueang Kanchanaburi",
  "Sai Yok",
  "Bo Phloi",
  "Si Sawat",
  "Thong Pha Phum",
  "Sangkhla Buri",
  "Huai Krachao",
  "Tha Maka",
  "Tha Muang",
  "Phanom Thuan",
  "Nong Prue",
  "Lao Khwan",
  "Dan Makham Tia",
  "Phang Nga",
  "Takua Pa",
  "Kapong",
  "Thai Mueang",
  "Takua Thung",
  "Mueang Phang Nga",
  "Khura Buri",
  "Koh Yao",
  "Phatthalung",
  "Khuan Khanun",
  "Kong Ra",
  "Pa Phayom",
  "Pa Bon",
  "Si Banphot",
  "Tamot",
  "Bang Kaeo",
  "Srinagarindra",
  "Mueang Phatthalung",
  "Lam Thap",
  "Khlong Thom",
  "Ko Lanta",
  "Khao Phanom",
  "Nuea Khlong",
  "Ao Luek",
  "Plai Phraya",
  "Krabi Noi",
  "Krabi Yai",
  "Pak Nam",
  "Phi Phi Islands",
  "Mueang Trang",
  "Kantang",
  "Nai Mueang",
  "Yan Ta Khao",
  "Sikao",
  "Huai Yot",
  "Wang Wiset",
  "Ratsada",
  "Palian",
  "Nai Mueang",
  "Ratsada",
  "Nai Mueang",
  "Pak Nam",
  "Na Khu",
  "Phon Na Kaeo",
  "Non Sa-at",
  "Chai Wan",
  "Kut Chap",
  "Phibun Rak",
  "Kumphawapi",
  "Ban Dung",
  "Nong Wua So",
  "Ban Phue",
  "Nam Som",
  "Nong Han",
  "Thung Fon",
  "Mueang Bueng Kan",
  "Phon Charoen",
  "Si Wilai",
  "Seka",
  "Pak Khat",
  "Bung Khla",
  "Bueng Khong Long",
  "Sang Khom",
  "Sang Khom",
  "Tha Bo",
  "Fao Rai",
  "Rattanawapi",
  "Si Chiang Mai",
  "Phon Phisai",
  "Sakhrai",
  "Sao Hai",
  "Nong Saeng",
  "Tha Sae",
  "Pha Yoon",
  "Phan Thong",
  "Mueang Chonburi",
  "Koh Si Chang",
  "Bang Lamung",
  "Ko Si Chang",
  "Phanat Nikhom",
  "Ban Bueng",
  "Si Racha",
  "Ko Sichang",
  "Ban Bueng",
  "Ko Sichang",
  "Ban Bueng",
  "Mueang Chanthaburi",
  "Khlung",
  "Makham",
  "Na Yai Am",
  "Tha Mai",
  "Pong Nam Ron",
  "Soi Dao",
  "Kaeng Hang Maeo",
  "Laem Sing",
  "Phichit",
  "Taphan Hin",
  "Bang Mun Nak",
  "Pho Prathap Chang",
  "Sam Ngam",
  "Pho Thale",
  "Nong Bua",
  "Bueng Na Rang",
  "Sak Lek",
  "Tap Khlo",
  "Wachira Barami",
  "Mueang Nakhon Nayok",
  "Ban Na",
  "Pak Phli",
  "Ongkharak",
  "Phu Khiao",
  "Kaset Sombun",
  "Bamnet Narong",
  "Chaturat",
  "Phakdi Chumphon",
  "Hua Taphan",
  "Mueang Amnat Charoen",
  "Mueang Yasothon",
  "Kho Wang",
  "Kham Khuean Kaeo",
  "Thai Charoen",
  "Sam Chuk",
  "Si Prachan",
  "Doem Bang Nang Buat",
  "Dan Chang",
  "Bang Pla Ma",
  "Mueang Suphan Buri",
  "Nakhon Luang",
  "Bang Pahan",
  "Bang Sai",
  "Bang Ban",
  "Uthai",
  "Sena",
  "Wang Noi",
  "Phak Hai",
  "Ban Phraek",
  "Phachi",
  "Maha Rat",
  "Bang Pa-in",
  "Nong Khai",
  "Tha Bo",
  "Pak Khat",
  "Phon Charoen",
  "So Phisai",
  "Mueang Bueng Kan",
  "Nong Khai",
  "Tha Bo",
  "Pak Khat",
  "Phon Charoen",
  "So Phisai",
  "Bueng Khong Long",
  "Phon Phisai",
  "Si Chiang Mai",
  "Sakhrai",
  "Chai Wan",
  "Kut Chap",
  "Non Sa-at",
  "Chai Wan",
  "Kut Chap",
  "Non Sa-at",
];

export default PakistanCities;
