import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../components/ReduxProvider";
import ClientWrapper from "../components/ClientWrapper";
import SessionProviderWrapper from "../components/SessionProviderWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import AppDataProvider from "@/context";
const inter = Inter({ subsets: ["latin"] });
import AppInitializer from "@/store/slices/AppInitializer";
// import socket from "@/services/socket"
export const metadata: Metadata = {
  title: "Asia Jobs Swipe | Asia's First Job Search Engine",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/toaster";
import Socket from "@/services/socket";
// import MessageListener from '@/services/MessageListener';
import { NotificationProvider } from "@/services/NotificationProvider";
import TopLoader from "@/components/TopLoader";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ fontFamily: "'SfUi', sans-serif" }}
      >
        <SessionProviderWrapper>
          <ReduxProvider>
            <NotificationProvider>
              <AppInitializer />
              <Socket />
              {/* <MessageListener /> */}
              <AppDataProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  <TopLoader />
                  <Toaster />
                  {children}
                </ThemeProvider>
              </AppDataProvider>
            </NotificationProvider>
          </ReduxProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
